### ISSUE TITLE
ltex in VSCode:  Request ltex/workspaceSpecificConfiguration failed with message: s[e] is not iterable

### ISSUE THREAD

**Issue by janpb** [valentjn/ltex-ls#88]
Locally installed ltex-ls is not working in VSCode.

**Expecting** : ltex-ls indicate typos etc. 
**Observing**: No indication of typos

 After opening any LaTeX file, ltex-ls reports following error:
```
The following exception occurred:
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request ltex/workspaceSpecificConfiguration failed with message: s[e] is not iterable
[Info  - 4:52:35 PM] Starting ltex-ls...
Jul 22, 2021 4:52:37 PM org.bsplines.ltexls.server.LtexLanguageServer initialize
INFO: ltex-ls 12.3.0 - initializing...
Jul 22, 2021 4:52:37 PM org.bsplines.ltexls.server.LtexLanguageServer initialize
INFO: Setting locale to 'en'
Jul 22, 2021 4:52:38 PM org.bsplines.ltexls.server.LtexTextDocumentService lambda$didOpen$0
WARNING: The following exception occurred:
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request ltex/workspaceSpecificConfiguration failed with message: s[e] is not iterable
at java.base/java.util.concurrent.CompletableFuture.reportGet(Unknown Source)
at java.base/java.util.concurrent.CompletableFuture.get(Unknown Source)
at org.bsplines.ltexls.server.LtexTextDocumentItem.check(LtexTextDocumentItem.java:449)
at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndGetDiagnostics(LtexTextDocumentItem.java:342)
at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnostics(LtexTextDocumentItem.java:319)
at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache(LtexTextDocumentItem.java:308)
at org.bsplines.ltexls.server.LtexTextDocumentService.lambda$didOpen$0(LtexTextDocumentService.java:160)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request ltex/workspaceSpecificConfiguration failed with message: s[e] is not iterable
at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	... 6 more
```

The ltex client is reporting everything is working fine (see below), but  not indicating any typos or other language related issues. The examples in walkthrough  from vscode-ltex (https://github.com/valentjn/vscode-ltex/tree/develop/walkthrough/en) do not indicate expected typos.

Same result using different Java versions (8,10,11), including AdoptOpenJDK (unsetting Java Path).

ltex-client  log:
```
2021-07-22T14:34:16.214Z Info: Setting LTeX UI language to 'en-us'.
2021-07-22T14:34:16.215Z Info: Loading i18n messages...
2021-07-22T14:34:16.215Z Info: Loading default i18n messages...
2021-07-22T14:34:16.218Z Info: 
2021-07-22T14:34:16.218Z Info: ltex.ltex-ls.path set to '/opt/ltex-ls'.
2021-07-22T14:34:16.218Z Info: 
2021-07-22T14:34:16.218Z Info: ltex.java.path set to '/usr/lib/jvm/default/'.
2021-07-22T14:34:16.218Z Info: Using ltex-ls from '/opt/ltex-ls'.
2021-07-22T14:34:16.218Z Info: Using Java from '/usr/lib/jvm/default/'.
2021-07-22T14:34:16.229Z Info: Testing ltex-ls...
2021-07-22T14:34:16.229Z Info:   Command: "/opt/ltex-ls/bin/ltex-ls"
2021-07-22T14:34:16.229Z Info:   Arguments: ["--version"]
2021-07-22T14:34:16.229Z Info:   env['JAVA_HOME']: "/usr/lib/jvm/default/"
2021-07-22T14:34:16.229Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-07-22T14:34:16.624Z Info: Test successful!
2021-07-22T14:34:16.626Z Info: 
2021-07-22T14:34:16.632Z Info: Starting ltex-ls...
2021-07-22T14:34:16.632Z Info:   Command: "/opt/ltex-ls/bin/ltex-ls"
2021-07-22T14:34:16.632Z Info:   Arguments: []
2021-07-22T14:34:16.632Z Info:   env['JAVA_HOME']: "/usr/lib/jvm/default/"
2021-07-22T14:34:16.632Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-07-22T14:34:16.632Z Info: 
```
ltex-ls version:

```
ltex-ls -V
{
  "ltex-ls": "12.3.0",
  "java": "11.0.11"
}
```
VSCode:
```
Version: 1.58.0
Commit: 2d23c42a936db1c7b3b06f918cde29561cc47cd6
Date: 2021-07-12T23:51:36.303Z
Electron: 12.0.15
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Linux x64 5.13.4-arch1-1
```

**Comment by valentjn** [comment]
- Please [follow the bug report template](https://valentjn.github.io/vscode-ltex/docs/contributing-code-issues.html#how-to-report-bugs) and fill in all the info. In particular, the settings and the LSP trace are missing (set [`ltex.trace.server`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltextraceserver) to `"messages"`).
- Does it work for the versions of vscode-ltex that automatically download LT<sub>E</sub>X LS (that's default when you install the extension from the VS Marketplace without using any special settings) or that already include LT<sub>E</sub>X LS (the ones with `-offline` from the [GitHub releases page](https://github.com/valentjn/vscode-ltex/releases/latest))? [It is not recommended to install LT<sub>E</sub>X LS manually when using vscode-ltex.](https://valentjn.github.io/vscode-ltex/docs/installation-and-usage.html#offline-installation)
- I don't see why you should be able to reproduce the problem with Java 8 or 10. LT<sub>E</sub>X LS needs Java 11, otherwise it will not even start.

**Comment by janpb** [comment]
**Describe the bug**

ltex is not indicating typos in VSCode. Java and ltex-ls are automatically installed by the extension. I did check if the theme is somehow blocking/masking the visual indications, but the default theme did not indicate  typos as well. 

**Steps to reproduce**

1. Install ltex and LaTeX workshop
2. Open LaTeX file with typos


**Expected behavior**
Typos are indicated as described int he documentation

**Sample document**
Example from the ltex repo: https://github.com/valentjn/vscode-ltex/tree/develop/walkthrough/en

<details>

```latex
\section{\LaTeX{} Example}

This is a sentence \emph{without any errors.}
This is a sentence \emph{with a speling error.}
Finally, this is a sentence \emph{with an grammar error.}

```

</details>

**LTeX configuration**

<details>

```
{
  "enabled": [
    "bibtex",
    "html",
    "latex",
    "markdown",
    "org",
    "restructuredtext",
    "rsweave"
  ],
  "language": "en-US",
  "dictionary": {
    "en-US": [
      "adaptivity",
      "precomputed",
      "subproblem",
      ":~/.config/vscode/ltex-dict/ltex.dictionary.en-US.txt"
    ],
    "de-CH": [
      "B-Splines",
      ":~/.config/vscode/ltex-dict/ltex.dictionary.de-CH.txt"
    ],
    "ltex.disabledRules": {
      "en-US": [
        ":~/.config/vscode/ltex.disabledRules.en-US.txt"
      ],
      "de-CH": [
        ":~/.config/vscode/ltex.disabledRules.de-CH.txt"
      ]
    }
  },
  "disabledRules": {},
  "enabledRules": {},
  "hiddenFalsePositives": {},
  "bibtex": {
    "fields": {}
  },
  "latex": {
    "commands": {},
    "environments": {}
  },
  "markdown": {
    "nodes": {}
  },
  "configurationTarget": {
    "dictionary": "userExternalFile",
    "disabledRules": "userExternalFile",
    "hiddenFalsePositives": "userExternalFile"
  },
  "additionalRules": {
    "enablePickyRules": false,
    "motherTongue": "de-CH",
    "languageModel": "",
    "neuralNetworkModel": "",
    "word2VecModel": ""
  },
  "ltex-ls": {
    "path": "",
    "languageToolHttpServerUri": "",
    "logLevel": "fine"
  },
  "java": {
    "path": "",
    "forceTrySystemWide": false,
    "initialHeapSize": 64,
    "maximumHeapSize": 512
  },
  "sentenceCacheSize": 2000,
  "diagnosticSeverity": "information",
  "checkFrequency": "edit",
  "clearDiagnosticsWhenClosingFile": true,
  "statusBarItem": false,
  "trace": {
    "server": "verbose"
  }
}
```

</details>

**"LTeX Language Server" log file**
First, reproduce the bug. Then, go to `View` → `Output` and select `LTeX Language Server` in the drop-down list. Paste this log here:

<details>

```
[Info  - 2:41:44 PM] Starting ltex-ls...
Jul 23, 2021 2:41:46 PM org.bsplines.ltexls.server.LtexLanguageServer initialize
INFO: ltex-ls 12.3.0 - initializing...
Jul 23, 2021 2:41:46 PM org.bsplines.ltexls.server.LtexLanguageServer initialize
INFO: Setting locale to 'en'
Jul 23, 2021 2:41:46 PM org.bsplines.ltexls.server.LtexTextDocumentService lambda$didOpen$0
WARNING: The following exception occurred:
java.util.concurrent.ExecutionException: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request ltex/workspaceSpecificConfiguration failed with message: s[e] is not iterable
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2069)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.check(LtexTextDocumentItem.java:449)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndGetDiagnostics(LtexTextDocumentItem.java:342)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnostics(LtexTextDocumentItem.java:319)
	at org.bsplines.ltexls.server.LtexTextDocumentItem.checkAndPublishDiagnosticsWithoutCache(LtexTextDocumentItem.java:308)
	at org.bsplines.ltexls.server.LtexTextDocumentService.lambda$didOpen$0(LtexTextDocumentService.java:160)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: org.eclipse.lsp4j.jsonrpc.ResponseErrorException: Request ltex/workspaceSpecificConfiguration failed with message: s[e] is not iterable
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.handleResponse(RemoteEndpoint.java:209)
	at org.eclipse.lsp4j.jsonrpc.RemoteEndpoint.consume(RemoteEndpoint.java:193)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.handleMessage(StreamMessageProducer.java:194)
	at org.eclipse.lsp4j.jsonrpc.json.StreamMessageProducer.listen(StreamMessageProducer.java:94)
	at org.eclipse.lsp4j.jsonrpc.json.ConcurrentMessageProcessor.run(ConcurrentMessageProcessor.java:113)
	... 6 more


```

</details>

**"LTeX Language Client" log file**
First, set the `ltex.trace.server` setting in your `settings.json` to `"verbose"`. Then, reload the VS Code window and reproduce the bug. Go to `View` → `Output` and select `LTeX Language Client` in the drop-down list. Paste this log here (note: it will contain your checked document):

<details>

```
2021-07-23T12:41:44.601Z Info: Setting LTeX UI language to 'en-us'.
2021-07-23T12:41:44.601Z Info: Loading i18n messages...
2021-07-23T12:41:44.601Z Info: Loading default i18n messages...
2021-07-23T12:41:44.602Z Info: 
2021-07-23T12:41:44.602Z Info: ltex.ltex-ls.path not set.
2021-07-23T12:41:44.602Z Info: Searching for ltex-ls in '/home/jpb/.config/vscode/extensions/valentjn.vscode-ltex-10.5.0/lib'...
2021-07-23T12:41:44.603Z Info: ltex-ls found in '/home/jpb/.config/vscode/extensions/valentjn.vscode-ltex-10.5.0/lib/ltex-ls-12.3.0'.
2021-07-23T12:41:44.603Z Info: 
2021-07-23T12:41:44.603Z Info: ltex.java.path not set.
2021-07-23T12:41:44.603Z Info: Using ltex-ls from '/home/jpb/.config/vscode/extensions/valentjn.vscode-ltex-10.5.0/lib/ltex-ls-12.3.0'.
2021-07-23T12:41:44.603Z Info: Using Java from PATH or JAVA_HOME (may fail if not installed).
2021-07-23T12:41:44.603Z Info: Testing ltex-ls...
2021-07-23T12:41:44.603Z Info:   Command: "/home/jpb/.config/vscode/extensions/valentjn.vscode-ltex-10.5.0/lib/ltex-ls-12.3.0/bin/ltex-ls"
2021-07-23T12:41:44.603Z Info:   Arguments: ["--version"]
2021-07-23T12:41:44.603Z Info:   env['JAVA_HOME']: undefined
2021-07-23T12:41:44.603Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-07-23T12:41:44.957Z Info: Test successful!
2021-07-23T12:41:44.957Z Info: 
2021-07-23T12:41:44.962Z Info: Starting ltex-ls...
2021-07-23T12:41:44.962Z Info:   Command: "/home/jpb/.config/vscode/extensions/valentjn.vscode-ltex-10.5.0/lib/ltex-ls-12.3.0/bin/ltex-ls"
2021-07-23T12:41:44.962Z Info:   Arguments: []
2021-07-23T12:41:44.962Z Info:   env['JAVA_HOME']: undefined
2021-07-23T12:41:44.962Z Info:   env['JAVA_OPTS']: "-Xms64m -Xmx512m"
2021-07-23T12:41:44.962Z Info: 
[Trace - 2:41:44 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 38170,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.58.0"
    },
    "locale": "en-us",
    "rootPath": "/home/jpb/project/bugreports/ltex",
    "rootUri": "file:///home/jpb/project/bugreports/ltex",
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "didChangeWatchedFiles": {
                "dynamicRegistration": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "configuration": true,
            "workspaceFolders": true,
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            }
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                },
                "codeDescriptionSupport": true,
                "dataSupport": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "insertReplaceSupport": true,
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    }
                },
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    },
                    "activeParameterSupport": true
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "labelSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                },
                "honorsChangeAnnotations": false
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true,
                "prepareSupportDefaultBehavior": 1,
                "honorsChangeAnnotations": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": true
                }
            },
            "showDocument": {
                "support": true
            },
            "workDoneProgress": true
        },
        "general": {
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0"
            }
        }
    },
    "initializationOptions": {
        "locale": "en",
        "customCapabilities": {
            "workspaceSpecificConfiguration": true
        }
    },
    "trace": "verbose",
    "workspaceFolders": [
        {
            "uri": "file:///home/jpb/project/bugreports/ltex",
            "name": "ltex"
        }
    ]
}


[Trace - 2:41:46 PM] Received response 'initialize - (0)' in 1274ms.
Result: {
    "capabilities": {
        "textDocumentSync": 1,
        "codeActionProvider": {
            "codeActionKinds": [
                "quickfix.ltex.acceptSuggestions"
            ]
        },
        "executeCommandProvider": {
            "commands": [
                "_ltex.checkDocument",
                "_ltex.getServerStatus"
            ]
        }
    }
}


[Trace - 2:41:46 PM] Sending notification 'initialized'.
Params: {}


[Trace - 2:41:46 PM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "ltex": {
            "enabled": [
                "bibtex",
                "html",
                "latex",
                "markdown",
                "org",
                "restructuredtext",
                "rsweave"
            ],
            "language": "en-US",
            "dictionary": {
                "en-US": [
                    "adaptivity",
                    "precomputed",
                    "subproblem",
                    ":~/.config/vscode/ltex-dict/ltex.dictionary.en-US.txt"
                ],
                "de-CH": [
                    "B-Splines",
                    ":~/.config/vscode/ltex-dict/ltex.dictionary.de-CH.txt"
                ],
                "ltex.disabledRules": {
                    "en-US": [
                        ":~/.config/vscode/ltex.disabledRules.en-US.txt"
                    ],
                    "de-CH": [
                        ":~/.config/vscode/ltex.disabledRules.de-CH.txt"
                    ]
                }
            },
            "disabledRules": {},
            "enabledRules": {},
            "hiddenFalsePositives": {},
            "bibtex": {
                "fields": {}
            },
            "latex": {
                "commands": {},
                "environments": {}
            },
            "markdown": {
                "nodes": {}
            },
            "configurationTarget": {
                "dictionary": "userExternalFile",
                "disabledRules": "userExternalFile",
                "hiddenFalsePositives": "userExternalFile"
            },
            "additionalRules": {
                "enablePickyRules": false,
                "motherTongue": "de-CH",
                "languageModel": "",
                "neuralNetworkModel": "",
                "word2VecModel": ""
            },
            "ltex-ls": {
                "path": "",
                "languageToolHttpServerUri": "",
                "logLevel": "fine"
            },
            "java": {
                "path": "",
                "forceTrySystemWide": false,
                "initialHeapSize": 64,
                "maximumHeapSize": 512
            },
            "sentenceCacheSize": 2000,
            "diagnosticSeverity": "information",
            "checkFrequency": "edit",
            "clearDiagnosticsWhenClosingFile": true,
            "statusBarItem": false,
            "trace": {
                "server": "verbose"
            }
        }
    }
}


[Trace - 2:41:46 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "file:///home/jpb/project/bugreports/ltex/example/example.tex",
        "languageId": "latex",
        "version": 1,
        "text": "\\section{\\LaTeX{} Example}\n\nThis is a sentence \\emph{without any errors.}\nThis is a sentence \\emph{with a speling error.}\nFinally, this is a sentence \\emph{with an grammar error.}\n"
    }
}


[Trace - 2:41:46 PM] Sending request 'textDocument/codeAction - (1)'.
Params: {
    "textDocument": {
        "uri": "file:///home/jpb/project/bugreports/ltex/example/example.tex"
    },
    "range": {
        "start": {
            "line": 0,
            "character": 0
        },
        "end": {
            "line": 0,
            "character": 0
        }
    },
    "context": {
        "diagnostics": []
    }
}


[Trace - 2:41:46 PM] Received request 'window/workDoneProgress/create - (1)'.
Params: {
    "token": "{\"uri\":\"file:///home/jpb/project/bugreports/ltex/example/example.tex\",\"operation\":\"checkDocument\",\"uuid\":\"f4c179d8-0236-3eed-1b6b-a4080154307f\"}"
}


[Trace - 2:41:46 PM] Sending response 'window/workDoneProgress/create - (1)'. Processing request took 1ms
No result returned.


[Trace - 2:41:46 PM] Received response 'textDocument/codeAction - (1)' in 8ms.
Result: []


[Trace - 2:41:46 PM] Received notification '$/progress'.
Params: {
    "token": "{\"uri\":\"file:///home/jpb/project/bugreports/ltex/example/example.tex\",\"operation\":\"checkDocument\",\"uuid\":\"f4c179d8-0236-3eed-1b6b-a4080154307f\"}",
    "value": {
        "kind": "begin",
        "title": "Checking document",
        "cancellable": false,
        "message": "file:///home/jpb/project/bugreports/ltex/example/example.tex"
    }
}


[Trace - 2:41:46 PM] Received request 'workspace/configuration - (2)'.
Params: {
    "items": [
        {
            "scopeUri": "file:///home/jpb/project/bugreports/ltex/example/example.tex",
            "section": "ltex"
        }
    ]
}


[Trace - 2:41:46 PM] Sending response 'workspace/configuration - (2)'. Processing request took 0ms
Result: [
    {
        "enabled": [
            "bibtex",
            "html",
            "latex",
            "markdown",
            "org",
            "restructuredtext",
            "rsweave"
        ],
        "language": "en-US",
        "dictionary": {
            "en-US": [
                "adaptivity",
                "precomputed",
                "subproblem",
                ":~/.config/vscode/ltex-dict/ltex.dictionary.en-US.txt"
            ],
            "de-CH": [
                "B-Splines",
                ":~/.config/vscode/ltex-dict/ltex.dictionary.de-CH.txt"
            ],
            "ltex.disabledRules": {
                "en-US": [
                    ":~/.config/vscode/ltex.disabledRules.en-US.txt"
                ],
                "de-CH": [
                    ":~/.config/vscode/ltex.disabledRules.de-CH.txt"
                ]
            }
        },
        "disabledRules": {},
        "enabledRules": {},
        "hiddenFalsePositives": {},
        "bibtex": {
            "fields": {}
        },
        "latex": {
            "commands": {},
            "environments": {}
        },
        "markdown": {
            "nodes": {}
        },
        "configurationTarget": {
            "dictionary": "userExternalFile",
            "disabledRules": "userExternalFile",
            "hiddenFalsePositives": "userExternalFile"
        },
        "additionalRules": {
            "enablePickyRules": false,
            "motherTongue": "de-CH",
            "languageModel": "",
            "neuralNetworkModel": "",
            "word2VecModel": ""
        },
        "ltex-ls": {
            "path": "",
            "languageToolHttpServerUri": "",
            "logLevel": "fine"
        },
        "java": {
            "path": "",
            "forceTrySystemWide": false,
            "initialHeapSize": 64,
            "maximumHeapSize": 512
        },
        "sentenceCacheSize": 2000,
        "diagnosticSeverity": "information",
        "checkFrequency": "edit",
        "clearDiagnosticsWhenClosingFile": true,
        "statusBarItem": false,
        "trace": {
            "server": "verbose"
        }
    }
]


[Trace - 2:41:46 PM] Received request 'ltex/workspaceSpecificConfiguration - (3)'.
Params: {
    "items": [
        {
            "scopeUri": "file:///home/jpb/project/bugreports/ltex/example/example.tex",
            "section": "ltex"
        }
    ]
}


2021-07-23T12:41:46.266Z Info: Started watching external setting file '/home/jpb/.config/vscode/ltex-dict/ltex.dictionary.de-CH.txt'.
2021-07-23T12:41:46.267Z Info: Started watching external setting file '/home/jpb/.config/vscode/ltex-dict/ltex.dictionary.en-US.txt'.
[Trace - 2:41:46 PM] Sending response 'ltex/workspaceSpecificConfiguration - (3)'. Processing request took 5ms
[Trace - 2:41:46 PM] Received notification '$/progress'.
Params: {
    "token": "{\"uri\":\"file:///home/jpb/project/bugreports/ltex/example/example.tex\",\"operation\":\"checkDocument\",\"uuid\":\"f4c179d8-0236-3eed-1b6b-a4080154307f\"}",
    "value": {
        "kind": "end"
    }
}


2021-07-23T12:43:39.820Z Info: Creating bug report...
[Trace - 2:43:39 PM] Sending request 'workspace/executeCommand - (2)'.
Params: {
    "command": "_ltex.getServerStatus",
    "arguments": []
}



```

</details>

**Version information**

- Operating system: Linux (linux), x64, 5.13.4-arch1-1
- VS Code: 1.58.0
- vscode-ltex: 10.5.0
- ltex-ls: 12.3.0
- Java: 16.0.2

**Additional context/information**
You can add any other context or information about the problem here.
